site_name: MRCD
nav:
  - Home: README.md
  - Download: download.md
  - User Guide: user-guide.md
  - Slam Tutorial: slam-tutorial.md
  - Release Notes: release-notes.md
  - Contribute: contribute.md
  # - Contact: contact.md (ADD LATER)
  # - License: license.md (ADD LATER?)
  # - Acknowledgements: acknowledgements.md (ADD LATER?)
  - Cite: bibliography.md
  - Gallery: gallery.md
  # - Tutorials: tutorials.md
  - Publications: publications.md
  - Team: team.md
  # - Videos: videos.md (ADD LATER)
theme:
  name: readthedocs
  logo: img/logo.png