site_name: MRCD
repo_url: https://sm20598.github.io/MRCD/
nav:
  - Home: README.md
  - Download: download.md
  - User Guide: user-guide.md
  - SLAM Tutorial: slam-tutorial.md
  - Release Notes: release-notes.md
  - Contribute: contribute.md
  # - Contact: contact.md (ADD LATER)
  # - License: license.md (ADD LATER?)
  # - Acknowledgements: acknowledgements.md (ADD LATER?)
  # - Bibliography: bibliography.md
  - Gallery: gallery.md
  # - Tutorials: tutorials.md
  - Publications: publications.md
  - Team: team.md
  # - Videos: videos.md (ADD LATER)
theme:
  name: readthedocs
  logo: img/logo.png
extra_css:
  - style.css
plugins:
  - resize-images:
      source-dir: graphics
      target-dir: graphics_resized
      size: [600, 600]
      extensions: ['.png']
  - caption